spring:
  datasource:
    username: sa
    url: jdbc:h2:./data/product-db
    driverClassName: org.h2.Driver
    password: sa
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: 'true'

spring:
  application:
    name: "product-rates"
  config:
    activate:
      on-profile: default
